#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

#########################################################
# Node-specific configuration
#########################################################
beneficiary = "{{ beneficiary }}"
node_name = "{{ node_name }}"
network_name = "{{ network_name }}"
ipc_tx_batch_size = 1000
ipc_max_queued_batches = 10
# must be <= ipc_max_queued_batches
ipc_queued_batches_watermark = 7

statesync_threshold = 1200
statesync_max_concurrent_requests = 5

#########################################################
# Network-wide configuration
#########################################################

chain_id = 30143

[peer_discovery]
self_address = "{{ address_with_port }}" 
self_record_seq_num = 0
self_name_record_sig = "{{ record_sig }}"
refresh_period = 120
request_timeout = 5
unresponsive_prune_threshold = 3
last_participation_prune_threshold = 1000
min_num_peers = 160
max_num_peers = 250

[fullnode_raptorcast]
enable_publisher = true
enable_client = true
raptor10_fullnode_redundancy_factor = 3.0
max_group_size = 150
max_num_group = 3
round_span = 240
invite_lookahead = 120
max_invite_wait = 10
deadline_round_dist = 10
init_empty_round_span = 23
invite_future_dist_min = 1
invite_future_dist_max = 600
invite_accept_heartbeat_ms = 10000

[fullnode_raptorcast.full_nodes_prioritized]
identities = []

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8000
max_rtt_ms = 300
max_mbps = 1000

[[fullnode_dedicated.identities]]


#This section will be uncommented after most validators have joined the network
[blocksync_override]
peers = []
[statesync]
peers = []
